### ISSUE TITLE
icr on Mac Mojave 

### ISSUE THREAD

**Issue by Brandongoodman615** [crystal-community/icr#110]
When trying to build or install I get errors, package is installed and reinstalled. 

```
Error target icr failed to compile:
ld: library not found for -lssl (this usually means you need to install the development package for libssl)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/brandongoodman/Desktop/crystal/firstapp/icr/bin/icr'  -rdynamic  -lreadline -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre /usr/local/Cellar/crystal/0.30.1/embedded/lib/libgc.a -lpthread /usr/local/Cellar/crystal/0.30.1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/local/Cellar/crystal/0.30.1/embedded/lib -L/usr/lib -L/usr/local/lib`
```

**Comment by jwoertink** [comment]
Do you have this set?
```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
```

**Comment by Brandongoodman615** [comment]
not sure… should probably let you know i’m a noob and only been coding Ruby
for  >1year

**Comment by Brandongoodman615** [comment]
just run that in console?

**Comment by jwoertink** [comment]
Ah. Well then welcome! This env var is a little strange. It's more of a crystal thing than it is a ICR thing. [Check this out](https://crystal-lang.org/reference/installation/on_mac_osx_using_homebrew.html). 

Just open up your `~/.bash_profile`, and add this to the bottom.

```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
```

Then restart your terminal, and 🤞 hope that works. If not, then we can try something else.

**Comment by Brandongoodman615** [comment]
ok I think I did what you’re asking
I’m not real good with the terminal yet honestly
I did:
$ cd ~/
$ open -e .bash_profile
added the line you sent to the bottom, (I only have 2 other lines in that
file)
restarted terminal
navigated to my firstapp (my crystal app name)
$ cd icr
$ make
then get same errors

Sorry, but I have to go step by step as I don’t want to waste your time.

**Comment by jwoertink** [comment]
It's all good. If you get stuck, come hop in the chat https://gitter.im/crystal-lang/crystal someone can help walk you through it. Then if there is an actual bug, we can get a good idea on what it is and how to fix it.

**Comment by atatarenko** [comment]
I'm getting the same error even with `PKG_CONFIG_PATH` set. This is what I basically see
```zsh
➜  icr git:(master) sudo make install                                          
/usr/local/bin/shards build --release 
Dependencies are satisfied
Building: icr
Error target icr failed to compile:
ld: library not found for -lssl (this usually means you need to install the development package for libssl)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/andrey/projects/icr/bin/icr'  -rdynamic  -lreadline -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre /usr/local/Cellar/crystal/0.31.1/embedded/lib/libgc.a -lpthread /usr/local/Cellar/crystal/0.31.1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/local/Cellar/crystal/0.31.1/embedded/lib -L/usr/lib -L/usr/local/lib`

make: *** [build] Error 1
```

Some other outputs that might be useful
```zsh
➜  icr git:(master) echo $PKG_CONFIG_PATH                                                      
/usr/local/opt/openssl/lib/pkgconfig
➜  icr git:(master) command -v pkg-config > /dev/null && pkg-config --libs libssl                                               
-L/usr/local/Cellar/openssl/1.0.2t/lib -lssl
➜  icr git:(master) command -v pkg-config > /dev/null && pkg-config --libs libcrypto                            
-L/usr/local/Cellar/openssl/1.0.2t/lib -lcrypto
```

So it seems like the right linking but it still doesn't work. I've already tried reinstalling the crystal compiler and running it one more time.

**Comment by atatarenko** [comment]
I'm running into this issue on macOS Mojave 10.14.16 btw

**Comment by veelenga** [comment]
This is related to https://github.com/crystal-lang/crystal/issues/6875

**Comment by Sija** [comment]
Can be closed it seems.
