### ISSUE TITLE
Crashes when path contains spaces

### ISSUE THREAD

**Issue by stellarpower** [crystal-community/icr#112]
Hi,

Only just installed icr, it seems that it crashes when my `pwd` contains any spaces: 'executing' any command from the REPL returns the error:

`Error: unknown command: /first/part/of/path`

And then accessing `__` causes an unhandled IndexError and prints a stack trace.

More than happy to provide more info, please could you tell me what would be useful? I'm running Mint but have crystal installed via snap, as Ubuntu packages often lag quite a bit behind the latest.

Thanks for the good work, I have always been a fan of ruby for scripting and lighter purposes, and it looks like Crystal will take the approach one step further and remove the qualms I have with duck typing etc. for general use and make a much more useable language. For me, being able to use icr in the same way as irb will make it faster for me to learn and also keep the dynammic aspect of ruby that makes it useful as a language, so I appreciate the effort!

**Comment by veelenga** [comment]
Reproduced. Thanks for reporting, will take care.
