### ISSUE TITLE
Accepts one character & then hangs

### ISSUE THREAD

**Issue by AlectronikForge** [crystal-community/icr#135]
I've installed the versions from Arch AUR (both the regular as well as the git one, problem happens with both), went fine until I started it. The very first character I type gets displayed and then the app hangs, even CTRL-C doesn't terminate it, I have to close the terminal window.

Crystal version is 1.8.2 (2023-05-11).

Unfortunately I'm still too much of a newbie to Crystal to try to figure it out by myself. Maybe somebody can point me in the right direction?

**Comment by veelenga** [comment]
Hey. This repo is abandoned. Please use official crystal interpreter:

```
crystal -h  | grep interactive
    i/interactive            starts interactive Crystal
```

**Comment by veelenga** [comment]
@jwoertink we may probably need to add a note regarding the crystal interpreter to the readme and archive the repo. WDTY?

**Comment by jwoertink** [comment]
For sure. We can probably set the repo as archived and just add to the README.
