### ISSUE TITLE
Installation on Mac OS via brew

### ISSUE THREAD

**Issue by veelenga** [crystal-community/icr#2]
It would be awesome to easily install it via brew:

``` sh
$ brew install crystal-icr
```

or if it is possible:

``` sh
$ brew install icr
```

[Checkout](https://github.com/sdogruyol/homebrew-fast-http-server) an example of homebrew repository for crystal app.

**Comment by greyblake** [comment]
Thanks! I am Linux user, but I'll take a look)

**Comment by marceloboeira** [comment]
@greyblake I'm checking this out, can you create release package here at github?

**Comment by greyblake** [comment]
@marceloboeira Thanks for taking care of this! The current version is tagged ast `v0.1.0`

**Comment by marceloboeira** [comment]
@greyblake I'll update the formula with the tagged version. :+1:

**Comment by greyblake** [comment]
@marceloboeira  Obrigado! :-)

**Comment by marceloboeira** [comment]
@greyblake bitte schön!

**Comment by SebastianSzturo** [comment]
Any update on the brew formula?

**Comment by marceloboeira** [comment]
@SebastianSzturo indeed, I will have some free time tomorrow and I will try to work on it. However, it is quite simple work:

https://github.com/marceloboeira/homebrew-bojack/blob/master/bojack.rb

**Comment by ktaragorn** [comment]
This should be closed now no? https://github.com/Homebrew/homebrew-core/pull/8246

**Comment by ktaragorn** [comment]
For those following the track https://github.com/Homebrew/legacy-homebrew/pull/48340 -> https://github.com/Homebrew/homebrew-core/pull/1579 -> https://github.com/Homebrew/homebrew-core/pull/8246
