### ISSUE TITLE
Build failing on Archlinux

### ISSUE THREAD

**Issue by kofiasare** [crystal-community/icr#48]
==> Downloading crystal-icr PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
crystal-icr 0.2.14-1  (2017-01-31 21:18)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> y

==> crystal-icr dependencies:
 - crystal (already installed)
 - readline (already installed)
 - llvm (package found) [makedepend]

==> Continue building crystal-icr ? [Y/n]
==> -------------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for crystal-icr:
[sudo] password for fiifi: 
resolving dependencies...
looking for conflicting packages...

Packages (1) llvm-4.0.0-2

Total Download Size:    20.96 MiB
Total Installed Size:  140.08 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'llvm-4.0.0-2-x86_64.pkg.tar.xz' from mirror.f4st.host : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds----c  o  o  o  o  o  o  o  ]  66%
 llvm-4.0.0-2-x86_64                                                                         12.3 KiB  -821.84K/s --:-- [co  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  ]   llvm-4.0.0-2-x86_64                                                                         41.0 KiB  -509.15K/s --:-- [co  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  ]   llvm-4.0.0-2-x86_64                                                                        166.8 KiB  -180.01K/s --:-- [-C  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  ]   llvm-4.0.0-2-x86_64                                                                          7.0 MiB  84.7K/s 01:25 [----------------------------------------------------------------------] 100%
(1/1) checking keys in keyring                                                                                       [----------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                     [----------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                          [----------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                    [----------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                  [----------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) installing llvm                                                                                                [----------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: crystal-icr 0.2.14-1 (Fri May  5 16:34:20 GMT 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v0.2.14.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130    0   130    0     0    137      0 --:--:-- --:--:-- --:--:--   137
100 82111    0 82111    0     0  36474      0 --:--:--  0:00:02 --:--:--  205k
==> Validating source files with sha256sums...
    v0.2.14.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v0.2.14.tar.gz with bsdtar
==> Starting build()...
/usr/bin/crystal build --release -o bin/icr src/icr/cli.cr 
==> Starting check()...
/usr/bin/crystal build --release -o bin/icr src/icr/cli.cr 
/usr/bin/crystal spec
...................F......

Failures:

  1) icr command errors prints runtime error without crashing
     Failure/Error: output.should match /invalid Int32: 5a \(ArgumentError\)/

       Expected: "icr(0.22.0) > \"5a\".to_i\nInvalid Int32: 5a (ArgumentError)\n0x443f7b: *CallStack::unwind:Array(Pointer(Void)) at ??\n0x457875: to_i32 at /usr/lib/crystal/string.cr 418:5\n0x45776c: to_i at /usr/lib/crystal/string.cr 319:5\n0x442350: __icr_exec__ at /tmp/yaourt-tmp-fiifi/aur-crystal-icr/src/crystal-icr-0.2.14/.icr_ngi4kLvKTiCk0achuFw7bQ.cr 3:3\n0x43305d: __crystal_main at /tmp/yaourt-tmp-fiifi/aur-crystal-icr/src/crystal-icr-0.2.14/.icr_ngi4kLvKTiCk0achuFw7bQ.cr 5:26\n0x442229: main at /usr/lib/crystal/main.cr 12:15\n0x7f89a63c4511: __libc_start_main at ??\n0x43296a: _start at ??\n0x0: ??? at ??\nicr(0.22.0) >"
       to match: /invalid Int32: 5a \(ArgumentError\)/

     # spec/integration/icr_spec.cr:174

Finished in 58.34 seconds
26 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec spec/integration/icr_spec.cr:171 # icr command errors prints runtime error without crashing
make: *** [Makefile:10: test] Error 1
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Makepkg was unable to build crystal-icr.

**Comment by faustinoaq** [comment]
I was able to install crystal-icr via AUR on Manjaro Linux editing the PKGBUILD to match with master branch of this repo (non failing code)

```shell
# Maintainer: Oleh Prypin <aur@blaxpirit.com>
pkgname=crystal-icr
pkgver=master
pkgrel=1
pkgdesc="Interactive console for Crystal programming language"
arch=(i686 x86_64)
url='https://github.com/greyblake/crystal-icr'
license=(LGPL)
depends=('crystal' 'readline')
makedepends=('llvm')
source=("https://codeload.github.com/greyblake/crystal-icr/tar.gz/$pkgver")
sha256sums=('d8bfa3c769b7f45ce205f84c92db6c9a69250a2d52b7cb1191e5eb9059f0a568')

build() {
  cd "$pkgname-$pkgver"
  make
  crystal eval 'STDIN.blocking = true'
}

check() {
  cd "$pkgname-$pkgver"
  make test
  crystal eval 'STDIN.blocking = true'
}

package() {
  cd "$pkgname-$pkgver"
  install -Dm755 bin/icr "$pkgdir/usr/bin/icr"
}
```

Maybe @greyblake needs to release a new version and @BlaXpirit needs to update the PKGBUILD

**Comment by kofiasare** [comment]
Thanks @faustinoaq

**Comment by oprypin** [comment]
Still failing, still needs a new release.

**Comment by faustinoaq** [comment]
Maybe using [this comment](https://github.com/crystal-community/icr/issues/48#issuecomment-317153221) and updating sha256sums, also freezing to latest version instead of master.

**Comment by oprypin** [comment]
Disabled specs for a workaround.

**Comment by faustinoaq** [comment]
I think `crystal-icr` is working now on AUR, Should we close this ?

**Comment by veelenga** [comment]
@kofiasare can be closed?
