### ISSUE TITLE
Output of command only works once

### ISSUE THREAD

**Issue by beanilsson** [crystal-community/icr#49]
This is what happens when I'm trying to execute small code pieces within icr:
![screen shot 2017-05-24 at 14 45 46](https://cloud.githubusercontent.com/assets/13626169/26403786/cef99980-408f-11e7-8876-aeb2d411a3cb.png)

I only get an output on the first attempt. I'm running crystal within an Ubuntu Vagrant box.

**Comment by beanilsson** [comment]
I just realised that the mistake was my own. One cannot use single quotes for strings in crystal, but double quotes should be used. Funny though how icr seems to freeze when single quotes are used. Maybe there should be some sort of error message printed to the user?

**Comment by jwoertink** [comment]
The bug is that you used the Char literal and not String literal. Crystal throws an error for that I believe, so we just need to catch that error and return it. That should be an easy fix.
