### ISSUE TITLE
Feature: paste mode

### ISSUE THREAD

**Issue by Porcupine96** [crystal-community/icr#55]
How about adding a paste mode? :)

Something like:

![paste mode](http://imgur.com/jRZ8sw2.png)

I provided a very simple implementation in a PR. https://github.com/crystal-community/icr/pull/56

**Comment by jwoertink** [comment]
Looks like this was merged in. I think this can be closed.

**Comment by greyblake** [comment]
Yes, it was merged in https://github.com/crystal-community/icr/pull/56
