### ISSUE TITLE
Command type detection bug

### ISSUE THREAD

**Issue by ktaragorn** [crystal-community/icr#61]
Test case - `Reference.new == Reference.new` 
Even though this is an equality check, this is being caught as a `constant_assignment` command and so is wrongly treated. You do not get the output of the command.

**Comment by ktaragorn** [comment]
Is the `.+` in `/^[A-Z]+([a-z_0-9].+)?\s*\={1}[^=~]/` intentional or a bug? Seems like should be `+`

**Comment by ktaragorn** [comment]
also i think `\={1}` should be just `=`

**Comment by ktaragorn** [comment]
Ill try to create a PR into this tomorrow

**Comment by veelenga** [comment]
Yup, seems to be introduced in https://github.com/crystal-community/icr/pull/59.
