### ISSUE TITLE
Consider adding warning to readme

### ISSUE THREAD

**Issue by RX14** [crystal-community/icr#65]
See: https://github.com/crystal-lang/crystal/issues/5128

**Comment by oprypin** [comment]
Heck, add a warning at the start of each `icr` run

**Comment by greyblake** [comment]
LOL :)
I thought we get this complaint much earlier.

Not everyone reads README carefully, so I am for adding the warnings to the `icr` so it prints it on every start.
The message should warn about the following:
* Network operations
* File operations
* Random numbers
* Anything else?

**Comment by greyblake** [comment]
Maybe we can display the message when `icr` is running first time by the user?

**Comment by oprypin** [comment]
Just do it every time but add a flag to disable the warning and then a user
can add the flag in a bashrc alias

**Comment by RX14** [comment]
Or do it like GNU parallel's citation notice: you run `parallel --citation` and it silences the message forever.
