### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by faustinoaq** [crystal-community/icr#67]
Hi @veelenga @greyblake  ICR is being used in [Amber CLI](https://amberframework.org/guides#getting-started/cli/console.md). Would be useful to release a stable tag line `v0.3.0` or `v0.2.15` to avoid using master and avoid unexpected changes.

Thanks you crystal-community for maintain this shard! <3

**Comment by veelenga** [comment]
Done.

* https://github.com/crystal-community/icr/commit/a29c66fd7499b35845587e490ed166da6ecfdf1e
* https://github.com/crystal-community/icr/compare/v0.2.14...v0.3.0
* https://github.com/crystal-community/icr/releases/tag/v0.3.0

**Comment by faustinoaq** [comment]
> Will someone take care about AUR update?

I left a comment on AUR repo https://aur.archlinux.org/packages/crystal-icr/#news

**Comment by oprypin** [comment]
There's a "Flag package out-of-date" feature. But none of that is necessary anyway.
