### ISSUE TITLE
Updating README gif

### ISSUE THREAD

**Issue by jwoertink** [crystal-community/icr#76]
I tried to create a new gif to update the README, but I [ran in to an issue](https://github.com/asciinema/asciicast2gif/issues/29)

Here's the asciinema url https://asciinema.org/a/DGXTjBZQMq34ATzknGS1SWyfe if anyone wants to take a stab at turning it in to a gif.

**Comment by veelenga** [comment]
I can do that, but I think showing that usage warning in a demo is not necessary.

**Comment by jwoertink** [comment]
Ah, yeah. I guess that's true.

**Comment by Sija** [comment]
Can this issue be closed?
