### ISSUE TITLE
Reset does not work

### ISSUE THREAD

**Issue by Jens0512** [crystal-community/icr#78]
When i enter icr do whatever (same thing happens when i do nothing first also) and enter `reset`
I get the following error
```
undefined local variable or method 'reset'

  reset
  ^~~~~
```

**Comment by veelenga** [comment]
Do you use master branch? Reset feature was not included into the latest release, so it wouldn't work if you installed it using a package manager.

**Comment by Jens0512** [comment]
@veelenga I am on the master branch, and i did not install it using a package manager

**Comment by veelenga** [comment]
Does it work for you now? Or the issue still persists?
