### ISSUE TITLE
Thank you guys! 

### ISSUE THREAD

**Issue by greyblake** [crystal-community/icr#82]
Hey. I'd like to thank to all of you guys, who help maintain this repo. :heart:
Despite Crystal community is relatively small, I am very glad to see how friendly and inspiring it can be!
Thanks for replying to the new open issues, doing cleanups and improvements.
Without you this project (and some others) would be dead.

**Comment by veelenga** [comment]
@greyblake glad to here. And without you this project (and some others) would not exist :). You did a great job and we still happy to see your participation (approvals/ideas/development). I hope you still enjoy Crystal as well as Rust you do :)

**Comment by jwoertink** [comment]
I love being a part of a community that makes others feel welcomed to contribute and make great libs like this one! Here's to 2018 being even better 🎉
