### ISSUE TITLE
Support Emacs

### ISSUE THREAD

**Issue by brantou** [crystal-community/icr#84]
I create an emacs-plugin named [inf-crystal.el](https://github.com/brantou/inf-crystal.el).
**inf-crystal** provides a REPL buffer connected to a **ICR** subprocess.

Already submitted PR to melpa https://github.com/melpa/melpa/pull/5226

**Comment by veelenga** [comment]
Nice. Could you please add a new section **Editor integration** and a note about inf-crystal to note to ICR's readme?

**Comment by brantou** [comment]
👌, Thanks. https://github.com/crystal-community/icr/pull/85
