### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by JonnyCodewalker** [crystal-community/icr#87]
When attempting to use the makefile I was gretted with the 2 following errors:
"Cannot find -levent" and "Cannot find -lyaml".

I managed to fix that by temporarily renaming `libevent-2.1.so.6` to `libevent.so` and `libyaml-0.so.2` to `libyaml.so`.

After that the makefile worked, however in Order to then execute icr I had to rename them back and create a copy of the `libevent.so` so that `libevent.so` and `libevent-2.1.so.6` both exist.

I am not sure what the error here is, but maybe you can make sense of it. Fresh install of Solus, if that helps.

**Comment by Jens0512** [comment]
The problem is not in the makefile. It was just two libraries that was missing.
