### ISSUE TITLE
Enums error

### ISSUE THREAD

**Issue by komisan19** [crystal-community/icr#88]
Hi!
i study Crystal-lang document.
enum is error
so, i can't use enum : (

```
Syntax error in .icr_goOw6J5s0L5tnfIjIBE-kg.cr:2: can't define enum inside def
  enum Color
  ^
```

**Comment by veelenga** [comment]
@komisan19 thanks for reporting this. Please use master branch if you want to use enums. We will prepare a new release once we have enough changes to go out.

**Comment by komisan19** [comment]
thanks : )
