### ISSUE TITLE
add simple-prompt option

### ISSUE THREAD

**Issue by KINGSABRI** [crystal-community/icr#96]
hello there

would you please implement `--simple-prompt` option which hides `icr(0.24.2) >` to be just ` > ` or make an option to specify the prompt itself

Thanks!

**Comment by jwoertink** [comment]
Hey, thanks for your suggestion!

Do you have an example use case for this? Or maybe some reasoning behind the motivation for this feature? If you're just looking for aesthetics, icr currently supports a `paste` function which removes the `default_invitation`. Though, I don't ever use that feature, so I'm not sure what shape it's in lol.

**Comment by KINGSABRI** [comment]
Hey! 
This feature is implemented in `irb` and `pry` it makes the screen cleaner to work with especially when you explain, recording things 

Of course, there are many other/more important features like autocomplete but I understand the efforts you guys trying to do. 

Thanks you

**Comment by jwoertink** [comment]
wow, I never knew either of those had that option. If that's the case, I think this could be a valid option. It shouldn't be too difficult to add either.

**Comment by veelenga** [comment]
I will take care of it if you don't mind.
