### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jwoertink** [crystal-community/icr#99]
Not that this is a huge deal, but maybe this should be standardized? 

Now that the repo is under a new name, is it MIT, or still LGPL3?

https://github.com/crystal-community/icr/blob/master/shard.yml#L11
https://github.com/crystal-community/icr/blob/master/LGPL-LICENSE.txt

**Comment by jwoertink** [comment]
But since the repo is moved to the community, and has so many different people working on it, should we change this? Or do you think it's ok to leave as the LGPL, and then just update the shard file to match?

**Comment by veelenga** [comment]
Oh, good point. I don't have a strong opinion on this and is okay for MIT. Maybe @greyblake wants to say something as he added it originally?

**Comment by greyblake** [comment]
I used to be fan of GNU and used mostly GPL for my projects.
However MIT is much simpler.and more important gives more freedom. I am OK with switching to MIT (hope there are.no legal consequences?)
